name: Close resolved issues

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: blackchoey/stale@releases/v1.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been resolved and it will be closed if no further activity occurs within 3 days. Thank you for your contributions.'
        stale-issue-label: 'pending close'
        days-before-stale: 7
        only-labels: 'resolved'
        last-updated-user-type: 'collaborator'
        days-before-close: 3
        operations-per-run: 150
